In [1]:
import numpy as np
import pandas as pd

In [85]:
death = pd.read_csv('time_series_covid19_deaths_global.csv');
confirm= pd.read_csv('time_series_covid19_confirmed_global.csv')

In [82]:
#it is multiindex tuples it decuple the tuples 
index_val = [
    ('cse', 2019), ('cse', 2020), ('cse', 2021), ('cse', 2022),
    ('ece', 2019), ('ece', 2020), ('ece', 2021), ('ece', 2022)
]
multiindex= pd.MultiIndex.from_tuples(index_val,names=['Department','year'])
multiindex
#2it is product 
pd.MultiIndex.from_product([['cse','ece'],[2019,2020,2021,2022]])

MultiIndex([('cse', 2019),
            ('cse', 2020),
            ('cse', 2021),
            ('cse', 2022),
            ('ece', 2019),
            ('ece', 2020),
            ('ece', 2021),
            ('ece', 2022)],
           )

In [83]:
#creating a series multiindex object

s = pd.Series([1,2,3,4,5,6,7,8],index=multiindex)
s

Department  year
cse         2019    1
            2020    2
            2021    3
            2022    4
ece         2019    5
            2020    6
            2021    7
            2022    8
dtype: int64

In [16]:
s['cse']

year
2019    1
2020    2
2021    3
2022    4
dtype: int64

In [17]:
#unstack - convert multiindex into dataframe
s.unstack()

year        2019  2020  2021  2022
Department
cse            1     2     3     4
ece            5     6     7     8

In [18]:
#stack - convert dataframe into multiindex
temp = s.unstack()
temp.stack()

Department  year
cse         2019    1
            2020    2
            2021    3
            2022    4
ece         2019    5
            2020    6
            2021    7
            2022    8
dtype: int64

In [20]:
branch_df1 = pd.DataFrame(
    [
        [1,2],
        [3,4],
        [5,6],
        [7,8],
        [9,10],
        [11,12],
        [13,14],
        [15,16],
    ],

    index = multiindex,
    columns = ['avg_package','students']
)
branch_df1

                 avg_package  students
Department year
cse        2019            1         2
           2020            3         4
           2021            5         6
           2022            7         8
ece        2019            9        10
           2020           11        12
           2021           13        14
           2022           15        16

In [21]:
branch_df1.loc['cse']

      avg_package  students
year
2019            1         2
2020            3         4
2021            5         6
2022            7         8

In [24]:
branch_df1['avg_package']

Department  year
cse         2019     1
            2020     3
            2021     5
            2022     7
ece         2019     9
            2020    11
            2021    13
            2022    15
Name: avg_package, dtype: int64

In [25]:
#STACKING AND UNSTACKING

In [30]:
branch_df1.unstack().unstack()

             year  Department
avg_package  2019  cse            1
                   ece            9
             2020  cse            3
                   ece           11
             2021  cse            5
                   ece           13
             2022  cse            7
                   ece           15
students     2019  cse            2
                   ece           10
             2020  cse            4
                   ece           12
             2021  cse            6
                   ece           14
             2022  cse            8
                   ece           16
dtype: int64

In [36]:
branch_df1.unstack().stack().stack()

Department  year
cse         2019  avg_package     1
                  students        2
            2020  avg_package     3
                  students        4
            2021  avg_package     5
                  students        6
            2022  avg_package     7
                  students        8
ece         2019  avg_package     9
                  students       10
            2020  avg_package    11
                  students       12
            2021  avg_package    13
                  students       14
            2022  avg_package    15
                  students       16
dtype: int64

In [37]:
#WORKING WITH MULTIINDEX DATAFRAMES

In [44]:
import pandas as pd

# 1. Create the MultiIndex for the Columns (City, Metric)
columns_tuples = [
    ('delhi', 'avg_package'), ('delhi', 'students'),
    ('mumbai', 'avg_package'), ('mumbai', 'students')
]
col_index = pd.MultiIndex.from_tuples(columns_tuples, names=['City', 'Metric'])

# 2. Create the MultiIndex for the Rows (Department, Year)
row_tuples = [
    ('cse', 2019), ('cse', 2020), ('cse', 2021), ('cse', 2022),
    ('ece', 2019), ('ece', 2020), ('ece', 2021), ('ece', 2022)
]
row_index = pd.MultiIndex.from_tuples(row_tuples, names=['Department', 'Year'])

# 3. Define the exact matrix data from your image
data = [   # cse 2019,    # cse 2020,    # cse 2021,    # cse 2022,   # ece 2019,  # ece 2020,  # ece 2021
    [15, 16, 0, 0]   # ece 2022
]

# 4. Assemble the DataFrame
branch_df3 = pd.DataFrame(data, index=row_index, columns=col_index)

# Display the result
branch_df3

City                  delhi               mumbai
Metric          avg_package students avg_package students
Department Year
cse        2019          15       16           0        0
           2020          15       16           0        0
           2021          15       16           0        0
           2022          15       16           0        0
ece        2019          15       16           0        0
           2020          15       16           0        0
           2021          15       16           0        0
           2022          15       16           0        0

In [45]:
branch_df3.head(2)

City                  delhi               mumbai
Metric          avg_package students avg_package students
Department Year
cse        2019          15       16           0        0
           2020          15       16           0        0

In [47]:
branch_df3.shape

(8, 4)

In [48]:
branch_df3.info()

<class 'pandas.DataFrame'>
MultiIndex: 8 entries, ('cse', np.int64(2019)) to ('ece', np.int64(2022))
Data columns (total 4 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   (delhi, avg_package)   8 non-null      int64
 1   (delhi, students)      8 non-null      int64
 2   (mumbai, avg_package)  8 non-null      int64
 3   (mumbai, students)     8 non-null      int64
dtypes: int64(4)
memory usage: 423.0 bytes

In [49]:
#single row
branch_df3.loc[('cse',2022)]

City    Metric
delhi   avg_package    15
        students       16
mumbai  avg_package     0
        students        0
Name: (cse, 2022), dtype: int64

In [52]:
#multiple row
branch_df3.loc[('cse',2019):('ece',2020):2]

City                  delhi               mumbai
Metric          avg_package students avg_package students
Department Year
cse        2019          15       16           0        0
           2021          15       16           0        0
ece        2019          15       16           0        0

In [54]:
branch_df3.iloc[0:5:2]

City                  delhi               mumbai
Metric          avg_package students avg_package students
Department Year
cse        2019          15       16           0        0
           2021          15       16           0        0
ece        2019          15       16           0        0

In [56]:
#EXtracting cols

branch_df3['delhi']['students']

Department  Year
cse         2019    16
            2020    16
            2021    16
            2022    16
ece         2019    16
            2020    16
            2021    16
            2022    16
Name: students, dtype: int64

In [57]:
branch_df3.iloc[:,1:3]

City               delhi      mumbai
Metric          students avg_package
Department Year
cse        2019       16           0
           2020       16           0
           2021       16           0
           2022       16           0
ece        2019       16           0
           2020       16           0
           2021       16           0
           2022       16           0

In [59]:
#Extracting Both
branch_df3.iloc[[0,4],[1,2]]

City               delhi      mumbai
Metric          students avg_package
Department Year
cse        2019       16           0
ece        2019       16           0

In [63]:
#sort_index
branch_df3.sort_index(ascending = False)
branch_df3.sort_index(ascending=[False,True])
branch_df3.sort_index(level=1,ascending=[False])

City                  delhi               mumbai
Metric          avg_package students avg_package students
Department Year
cse        2022          15       16           0        0
ece        2022          15       16           0        0
cse        2021          15       16           0        0
ece        2021          15       16           0        0
cse        2020          15       16           0        0
ece        2020          15       16           0        0
cse        2019          15       16           0        0
ece        2019          15       16           0        0

In [65]:
#Transpose
branch_df3.transpose()

Department          cse                 ece
Year               2019 2020 2021 2022 2019 2020 2021 2022
City   Metric
delhi  avg_package   15   15   15   15   15   15   15   15
       students      16   16   16   16   16   16   16   16
mumbai avg_package    0    0    0    0    0    0    0    0
       students       0    0    0    0    0    0    0    0

In [68]:
#swaplevel
branch_df3.swaplevel(axis=1)

Metric          avg_package students avg_package students
City                  delhi    delhi      mumbai   mumbai
Department Year
cse        2019          15       16           0        0
           2020          15       16           0        0
           2021          15       16           0        0
           2022          15       16           0        0
ece        2019          15       16           0        0
           2020          15       16           0        0
           2021          15       16           0        0
           2022          15       16           0        0

In [69]:
#LONG VS WIDE DATA

In [74]:
#melt -> convert wide data into long data format

pd.DataFrame({'cse':[120]}).melt()

  variable  value
0      cse    120

In [75]:
pd.DataFrame({'cse':[120],'ece':[100],'mech':[50]})

   cse  ece  mech
0  120  100    50

In [78]:
pd.DataFrame({'cse':[120],'ece':[100],'mech':[50]}).melt(var_name='branch',value_name='num_students')

  branch  num_students
0    cse           120
1    ece           100
2   mech            50

In [86]:
death.head()

,Province/State,Country/Region,Lat,Long,1/22/20,1/23/20,1/24/20,1/25/20,1/26/20,1/27/20,...,12/24/22,12/25/22,12/26/22,12/27/22,12/28/22,12/29/22,12/30/22,12/31/22,1/1/23,1/2/23
0,NaN,Afghanistan,33.93911,67.709953,0,0,0,0,0,0,...,7845,7846,7846,7846,7846,7847,7847,7849,7849,7849
1,NaN,Albania,41.15330,20.168300,0,0,0,0,0,0,...,3595,3595,3595,3595,3595,3595,3595,3595,3595,3595
2,NaN,Algeria,28.03390,1.659600,0,0,0,0,0,0,...,6881,6881,6881,6881,6881,6881,6881,6881,6881,6881
3,NaN,Andorra,42.50630,1.521800,0,0,0,0,0,0,...,165,165,165,165,165,165,165,165,165,165
4,NaN,Angola,-11.20270,17.873900,0,0,0,0,0,0,...,1928,1928,1928,1930,1930,1930,1930,1930,1930,1930

In [87]:
death.head().melt()

            variable value
0     Province/State   NaN
1     Province/State   NaN
2     Province/State   NaN
3     Province/State   NaN
4     Province/State   NaN
...              ...   ...
5400          1/2/23  7849
5401          1/2/23  3595
5402          1/2/23  6881
5403          1/2/23   165
5404          1/2/23  1930

[5405 rows x 2 columns]

In [88]:
confirm.head()

,Province/State,Country/Region,Lat,Long,1/22/20,1/23/20,1/24/20,1/25/20,1/26/20,1/27/20,...,12/24/22,12/25/22,12/26/22,12/27/22,12/28/22,12/29/22,12/30/22,12/31/22,1/1/23,1/2/23
0,NaN,Afghanistan,33.93911,67.709953,0,0,0,0,0,0,...,207310,207399,207438,207460,207493,207511,207550,207559,207616,207627
1,NaN,Albania,41.15330,20.168300,0,0,0,0,0,0,...,333749,333749,333751,333751,333776,333776,333806,333806,333811,333812
2,NaN,Algeria,28.03390,1.659600,0,0,0,0,0,0,...,271194,271198,271198,271202,271208,271217,271223,271228,271229,271229
3,NaN,Andorra,42.50630,1.521800,0,0,0,0,0,0,...,47686,47686,47686,47686,47751,47751,47751,47751,47751,47751
4,NaN,Angola,-11.20270,17.873900,0,0,0,0,0,0,...,104973,104973,104973,105095,105095,105095,105095,105095,105095,105095

In [89]:
confirm.head().melt()

            variable   value
0     Province/State     NaN
1     Province/State     NaN
2     Province/State     NaN
3     Province/State     NaN
4     Province/State     NaN
...              ...     ...
5400          1/2/23  207627
5401          1/2/23  333812
5402          1/2/23  271229
5403          1/2/23   47751
5404          1/2/23  105095

[5405 rows x 2 columns]

In [92]:
death = death.melt(id_vars=['Province/State','Country/Region','Lat','Long'],var_name='date',value_name='num_deaths')
confirm =death.melt(id_vars=['Province/State','Country/Region','Lat','Long'],var_name='date',value_name='num_casess')

In [93]:
death

,Province/State,Country/Region,Lat,Long,date,num_deaths
0,NaN,Afghanistan,33.939110,67.709953,1/22/20,0
1,NaN,Albania,41.153300,20.168300,1/22/20,0
2,NaN,Algeria,28.033900,1.659600,1/22/20,0
3,NaN,Andorra,42.506300,1.521800,1/22/20,0
4,NaN,Angola,-11.202700,17.873900,1/22/20,0
...,...,...,...,...,...,...
311248,NaN,West Bank and Gaza,31.952200,35.233200,1/2/23,5708
311249,NaN,Winter Olympics 2022,39.904200,116.407400,1/2/23,0
311250,NaN,Yemen,15.552727,48.516388,1/2/23,2159
311251,NaN,Zambia,-13.133897,27.849332,1/2/23,4024
311252,NaN,Zimbabwe,-19.015438,29.154857,1/2/23,5637

In [94]:
confirm

,Province/State,Country/Region,Lat,Long,date,num_casess
0,NaN,Afghanistan,33.939110,67.709953,date,1/22/20
1,NaN,Albania,41.153300,20.168300,date,1/22/20
2,NaN,Algeria,28.033900,1.659600,date,1/22/20
3,NaN,Andorra,42.506300,1.521800,date,1/22/20
4,NaN,Angola,-11.202700,17.873900,date,1/22/20
...,...,...,...,...,...,...
622501,NaN,West Bank and Gaza,31.952200,35.233200,num_deaths,5708
622502,NaN,Winter Olympics 2022,39.904200,116.407400,num_deaths,0
622503,NaN,Yemen,15.552727,48.516388,num_deaths,2159
622504,NaN,Zambia,-13.133897,27.849332,num_deaths,4024
622505,NaN,Zimbabwe,-19.015438,29.154857,num_deaths,5637

In [ ]:
confirm.merge(death,on=['Province/State','Country/Region','Lat','Long'])[['Country/Region','date','num_deaths']]

In [96]:
import pandas as pd

# 1. Load the datasets
death = pd.read_csv('time_series_covid19_deaths_global.csv')
confirm = pd.read_csv('time_series_covid19_confirmed_global.csv')

# 2. Melt both datasets properly
death = death.melt(id_vars=['Province/State','Country/Region','Lat','Long'], var_name='date', value_name='num_deaths')
confirm = confirm.melt(id_vars=['Province/State','Country/Region','Lat','Long'], var_name='date', value_name='num_cases')

# 3. Include 'date' in the merge keys to prevent column renaming (date_x, date_y)
merged_df = confirm.merge(death, on=['Province/State','Country/Region','Lat','Long', 'date'])

# 4. Extract your desired columns safely
final_df = merged_df[['Country/Region', 'date', 'num_deaths']]

In [97]:
final_df

              Country/Region     date  num_deaths
0                Afghanistan  1/22/20           0
1                    Albania  1/22/20           0
2                    Algeria  1/22/20           0
3                    Andorra  1/22/20           0
4                     Angola  1/22/20           0
...                      ...      ...         ...
311248    West Bank and Gaza   1/2/23        5708
311249  Winter Olympics 2022   1/2/23           0
311250                 Yemen   1/2/23        2159
311251                Zambia   1/2/23        4024
311252              Zimbabwe   1/2/23        5637

[311253 rows x 3 columns]